### ISSUE TITLE
Bug: Install button not working

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/org.gustavoperedo.FontDownloader#2]
Hi, thank you a ton for maintaining the FontDownload flatpak. It's very useful to me.

Unfortunately, the app crashes when hitting the "install" button.

```
[dschier@nb01 ~]$ flatpak run org.gustavoperedo.FontDownloader 
Gtk-Message: 11:47:55.350: Failed to load module "canberra-gtk-module"

(fontdownloader:2): Gtk-WARNING **: 11:47:55.404: Duplicate child name in GtkStack: page0
Gtk-Message: 11:48:02.223: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:48:02.223: Failed to load module "canberra-gtk-module"
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:260: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
```

I am on Fedora 33.

Please feel free to get in touch, if I may provide any other helpful information or support you otherwise.

**Comment by GustavoPeredo** [comment]
Hello! Thank you for reporting this bug. Apparently this is an issue related to Xorg, if you want to use the application at the momment, I'd recommend to temporarily use Wayland, I'll be looking into the issue and hopefully a fix will be provided still today.

**Comment by GustavoPeredo** [comment]
I wasn't able to fix the issue, but I created an workaround by disabling multithreaded functions on X11. Apparently this is a recurring bug related to GTK -> Mesa -> X11 that I don't know how to fix.

I'll keep the issue open since there is no fix it as of yet (that I know of), but consider your problem solved (Fixed version is 4.2.1)

**Comment by GustavoPeredo** [comment]
It is possible to update to 4.2.1 using the following command:

`flatpak install https://dl.flathub.org/build-repo/38320/org.gustavoperedo.FontDownloader.flatpakref`

But I'd suggest to wait until it's deployed on flathub

**Comment by daniel-wtd** [comment]
Thanks a ton for this prompt fix :)

**Comment by daniel-wtd** [comment]
Tested and approved, that the "Install" Button is working. :+1:
